---
- name: Reload systemd
  command: systemctl daemon-reload
  when: not ansible_check_mode

- name: Restart trojan-go
  systemd:
    name: trojan-go
    state: restarted
  when: not ansible_check_mode
