export const RU_PHRASES = [
  // RU 2 words
  'новый день',
  'тихий вечер',
  'быстрый ответ',
  'хороший план',
  'простой путь',
  'верное решение',
  'чистый код',
  'новый проект',
  'важный шаг',
  'ясная мысль',
  'сильный ветер',
  'высокий дом',
  'мягкий свет',
  'тёплый чай',
  'холодный воздух',
  'длинная дорога',
  'тихий лес',
  'быстрый бег',
  'умный выбор',
  'верный друг',
  'новый мир',
  'лёгкий старт',
  'первый шаг',
  'быстрый рост',
  'ясный взгляд',
  'простой ответ',
  'сильная команда',
  'хороший результат',
  'новый уровень',
  'большой город',
  'тихий звук',
  'ясное утро',
  'дальний путь',
  'хороший день',
  'быстрый интернет',
  'простой текст',
  'новый файл',
  'лёгкая задача',
  'чистый экран',
  'быстрый доступ',
  'свежий воздух',
  'короткий путь',
  'тёплый вечер',
  'тихий город',
  'верный путь',
  'хороший сигнал',
  'новый шанс',
  'ясная цель',
  'простой стиль',
  'быстрый ответ',
  'новая идея',
  'старый дом',
  'быстрый поезд',
  'сильный дождь',
  'чистая вода',
  'светлый день',
  'ясное небо',
  'новый опыт',
  'добрый человек',
  'важная задача',
  'новый план',
  'короткий текст',
  'яркий свет',
  'тихий парк',
  'лёгкий ветер',
  'глубокий вдох',
  'новый маршрут',
  'быстрый шаг',
  'сильный сигнал',
  'высокий уровень',
  'простой способ',
  'новый сервер',
  'свежий хлеб',
  'мягкий диван',
  'новый ноутбук',
  'чистый стол',
  'быстрый старт',
  'хороший фильм',
  'новый дом',
  'старый мост',
  'ясный ответ',
  'важный вопрос',
  'быстрый рост',
  'новый этап',
  'тихая ночь',
  'новый год',
  'верный ответ',
  'простой язык',
  'быстрый поиск',
  'ясная логика',
  'новый взгляд',
  'простой пример',
  'тихий дождь',
  'быстрый результат',
  'ясный смысл',
  'новый стиль',
  'лёгкий путь',
  'быстрый поток',
  'новый метод',
  'сильный характер',

  // RU 3 words
  'новый хороший день',
  'тихий тёплый вечер',
  'быстрый точный ответ',
  'хороший простой план',
  'чистый новый код',
  'новый интересный проект',
  'важный первый шаг',
  'ясная умная мысль',
  'сильный холодный ветер',
  'высокий старый дом',
  'мягкий вечерний свет',
  'тёплый ароматный чай',
  'холодный утренний воздух',
  'длинная пустая дорога',
  'тихий зелёный лес',
  'быстрый лёгкий бег',
  'умный правильный выбор',
  'верный старый друг',
  'новый удивительный мир',
  'лёгкий быстрый старт',
  'первый смелый шаг',
  'быстрый стабильный рост',
  'ясный спокойный взгляд',
  'простой точный ответ',
  'сильная дружная команда',
  'хороший конечный результат',
  'новый высокий уровень',
  'большой шумный город',
  'тихий приятный звук',
  'ясное раннее утро',
  'дальний долгий путь',
  'хороший солнечный день',
  'быстрый домашний интернет',
  'простой понятный текст',
  'новый пустой файл',
  'лёгкая учебная задача',
  'чистый яркий экран',
  'быстрый удобный доступ',
  'свежий прохладный воздух',
  'короткий безопасный путь',
  'тёплый летний вечер',
  'тихий ночной город',
  'верный выбранный путь',
  'хороший стабильный сигнал',
  'новый редкий шанс',
  'ясная важная цель',
  'простой аккуратный стиль',
  'быстрый правильный ответ',
  'новая интересная идея',
  'старый деревянный дом',
  'быстрый скорый поезд',
  'сильный летний дождь',
  'чистая холодная вода',
  'светлый ясный день',
  'ясное голубое небо',
  'новый полезный опыт',
  'добрый честный человек',
  'важная сложная задача',
  'новый рабочий план',
  'короткий полезный текст',
  'яркий электрический свет',
  'тихий зелёный парк',
  'лёгкий прохладный ветер',
  'глубокий медленный вдох',
  'новый удобный маршрут',
  'быстрый уверенный шаг',
  'сильный стабильный сигнал',
  'высокий мировой уровень',
  'простой понятный способ',
  'новый рабочий сервер',
  'свежий тёплый хлеб',
  'мягкий удобный диван',
  'новый мощный ноутбук',
  'чистый рабочий стол',
  'быстрый лёгкий старт',
  'хороший интересный фильм',
  'новый красивый дом',
  'старый каменный мост',
  'ясный логичный ответ',
  'важный сложный вопрос',
  'быстрый уверенный рост',
  'новый важный этап',
  'тихая глубокая ночь',
  'новый счастливый год',
  'верный правильный ответ',
  'простой понятный язык',
  'быстрый точный поиск',
  'ясная строгая логика',
  'новый свежий взгляд',
  'простой учебный пример',
  'тихий мелкий дождь',
  'быстрый отличный результат',
  'ясный глубокий смысл',
  'новый современный стиль',
  'лёгкий короткий путь',
  'быстрый сильный поток',
  'новый полезный метод',
  'сильный уверенный характер',
  'быстрый лёгкий ветер',
  'новый важный шанс',
];

export const EN_PHRASES = [
  // EN 2 words
  'new day',
  'good plan',
  'fast response',
  'clear mind',
  'warm light',
  'cold wind',
  'small step',
  'big city',
  'good idea',
  'quick start',
  'simple code',
  'new project',
  'strong team',
  'fresh air',
  'quiet night',
  'long road',
  'short break',
  'good result',
  'easy task',
  'bright morning',
  'open door',
  'clear sky',
  'smart choice',
  'new chance',
  'fast internet',
  'clean screen',
  'warm tea',
  'cool water',
  'small house',
  'high tower',
  'quick move',
  'deep breath',
  'calm voice',
  'soft light',
  'good signal',
  'clear goal',
  'right path',
  'new file',
  'strong wind',
  'easy way',
  'quick answer',
  'good friend',
  'bright idea',
  'small world',
  'clear sound',
  'fast train',
  'good morning',
  'open mind',
  'calm night',
  'strong focus',
  'clear text',
  'simple task',
  'good code',
  'fast server',
  'new method',
  'small step',
  'deep focus',
  'bright sun',
  'open road',
  'clear voice',
  'calm mind',
  'fast growth',
  'good signal',
  'simple plan',
  'new start',
  'smart move',
  'clean code',
  'quiet room',
  'warm day',
  'cold night',
  'fast search',
  'strong signal',
  'clear logic',
  'small town',
  'deep sleep',
  'calm breath',
  'new level',
  'quick test',
  'easy answer',
  'fresh start',
  'bright sky',
  'clear vision',
  'smart idea',
  'good system',
  'fast build',
  'clean desk',
  'quick run',
  'warm sun',
  'cool breeze',
  'strong coffee',
  'deep voice',
  'good choice',
  'fast update',
  'open space',
  'calm sea',
  'good moment',
  'strong light',
  'simple way',
  'clear path',
  'fast flow',

  // EN 3 words
  'new bright day',
  'quiet warm evening',
  'fast clear response',
  'good simple plan',
  'clean modern code',
  'new interesting project',
  'important first step',
  'clear smart idea',
  'strong cold wind',
  'high old tower',
  'soft evening light',
  'warm green tea',
  'cold morning air',
  'long empty road',
  'quiet deep forest',
  'fast light run',
  'smart right choice',
  'loyal old friend',
  'new amazing world',
  'easy quick start',
  'first small step',
  'fast steady growth',
  'clear calm view',
  'simple short answer',
  'strong united team',
  'good final result',
  'new high level',
  'big busy city',
  'quiet soft sound',
  'clear early morning',
  'long distant path',
  'good sunny day',
  'fast home internet',
  'simple clear text',
  'new empty file',
  'easy training task',
  'clean bright screen',
  'fast easy access',
  'fresh cool air',
  'short safe path',
  'warm summer evening',
  'quiet night city',
  'right chosen path',
  'good stable signal',
  'new rare chance',
  'clear main goal',
  'simple clean style',
  'fast correct answer',
  'new smart idea',
  'old wooden house',
  'fast electric train',
  'strong summer rain',
  'clean cold water',
  'bright sunny day',
  'clear blue sky',
  'new useful experience',
  'kind honest person',
  'important complex task',
  'new working plan',
  'short helpful text',
  'bright electric light',
  'quiet green park',
  'light cool wind',
  'deep slow breath',
  'new easy route',
  'fast confident step',
  'strong stable signal',
  'high global level',
  'simple clear method',
  'new working server',
  'fresh warm bread',
  'soft comfortable sofa',
  'new powerful laptop',
  'clean working desk',
  'fast smooth start',
  'good interesting movie',
  'new beautiful house',
  'old stone bridge',
  'clear logical answer',
  'important hard question',
  'fast steady growth',
  'new important stage',
  'quiet deep night',
  'happy new year',
  'correct final answer',
  'simple human language',
  'fast accurate search',
  'clear strict logic',
  'new fresh view',
  'simple training example',
  'quiet light rain',
  'fast great result',
  'clear deep meaning',
  'new modern style',
  'easy short path',
  'fast strong flow',
  'new useful method',
  'strong confident character',
  'fast light wind',
  'new big chance',
];
