---
- name: Установить Nginx
  apt:
    name: "{{ nginx_package }}"
    state: present
    update_cache: yes

- name: Удалить default-конфиг
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Скопировать конфиг для {{ domain }}
  template:
    src: "{{ nginx_conf_src }}"
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx

- name: Включить сайт
  file:
    src: "{{ nginx_conf_path }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}.conf"
    state: link
  notify: Reload nginx

- name: Ensure ACME webroot exists
  file:
    path: /var/www/letsencrypt/.well-known/acme-challenge
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Validate nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0
